Follow
shinonome-inc/backend-final-assignment-yuki-Yuki-Takami pull request #4
Opened 2023-03-22 08:06 UTC by yuki00900

レビューをお願いします。

2023-03-22 23:59 UTC, ryo-thel commented on .github/pull_request_template.md
今回のみ中身をPRのコメントにコピペをお願いします。mainにマージ後の次回以降は大丈夫です。

2023-03-23 01:33 UTC, ryo-thel reviewed
確認をお願します！
追加でadminの対応もお願いします！

2023-03-23 01:33 UTC, ryo-thel commented on .github/pull_request_template.md
今回のみ中身をPRのコメントにコピペをお願いします！mainにマージ後の次回以降のPRでは大丈夫です！

2023-03-23 01:33 UTC, ryo-thel commented on accounts/views.py
> +        return super().post(request, *args, **kwargs)
同じユーザーでのフォローが何度でもできる状態だと思うのでFriendShipのモデルにユニーク制約を付けるなどで対応をお願いします

2023-03-23 23:24 UTC, yuki00900 commented on .github/pull_request_template.md
## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

これで大丈夫でしょうか。

2023-03-23 23:28 UTC, yuki00900 commented on accounts/views.py
> +        return super().post(request, *args, **kwargs)
localhostで確認して、フォローが何度でもできる状態ではなくなっているので
問題がないと思っていたのですが改善した方がよいでしょうか。

2023-03-23 23:28 UTC, yuki00900 commented on accounts/views.py
> +        return context
変更を加えたのですが大丈夫でしょうか。

2023-03-23 23:29 UTC, yuki00900 commented on accounts/views.py
>          return context
こちらも同様に変更を加えたのですが大丈夫でしょうか。

2023-03-24 11:04 UTC, ryo-thel commented on accounts/views.py
> +        return context
このままだと"following"フィールドは"User"モデルを参照しているため，フォローしたユーザーのIDでソートしている状態になってると思います。create_atを用いたり，FriendShipモデルのidを用いるとうまくいくと思うので調べてみてください！

2023-03-24 11:05 UTC, ryo-thel commented on .github/pull_request_template.md
チェックボックスの記入もお願いします！

2023-03-24 11:43 UTC, ryo-thel commented on accounts/views.py
> +        return super().post(request, *args, **kwargs)
通常の使用では複数回のフォローが起こる可能性は低いと思いますが、管理画面でデータを編集する場面などで、重複フォローが出来てしまうので，データの整合性を保つためにもモデルにユニーク制約を追加するのが無難かと思います。

2023-03-25 08:35 UTC, ryo-thel commented on accounts/views.py
> +        return context
すいません追加でListViewの機能が使えてない気がするのでそこも調べてみてください

2023-03-26 02:17 UTC, yuki00900 commented on accounts/views.py
> +        return context
ListViewの機能が使えていないということを上手く理解することができなかったので
どのように変更を加えればよいのかを教えていただけないでしょうか。

また、idを用いて変更を加えたつもりなのですが大丈夫でしょうか。

2023-03-26 02:17 UTC, yuki00900 commented on accounts/views.py
> +        return super().post(request, *args, **kwargs)
変更を加えたのですが大丈夫でしょうか。

2023-03-26 03:49 UTC, ryo-thel commented on .github/pull_request_template.md
adminの追加をお願いします！

2023-03-26 03:59 UTC, ryo-thel commented on accounts/views.py
> +        return context
follingもfollowing_idもどちらも主キーであるUserモデルのIDで管理されているため、今のままではUserが作成された順に並んでます。ですので一度フォローを外してから再びフォローをしても順番の変化が起きません。そのためcreate_atを用いないならFriendShipモデルのIDが必要になると思います。

2023-03-26 07:31 UTC, ryo-thel commented on accounts/views.py
> +        return context
外出中のため返信が遅くなり申し訳ありません。ListViewに関してですが
https://shinonome-inc.notion.site/View-template-context-34684a8b48b84bbc9d409863faf02317
ここにもあるようにListViewを使用した際に作成されるクエリセット（今回はUserモデルのobject_list)を利用していないことが気になりました。

2023-03-26 07:31 UTC, ryo-thel commented on accounts/views.py
> +        return context
リストの順番については大丈夫です！

2023-03-26 07:34 UTC, ryo-thel commented on .github/pull_request_template.md
ありがとうございます！

2023-03-26 07:38 UTC, ryo-thel commented on accounts/views.py
> +        return super().post(request, *args, **kwargs)
FriendShipのadminを操作すると重複フォローが出来る状態なので、できれば何かデータベースへの制約をかけてほしいです！

2023-03-26 08:00 UTC, yuki00900 commented on .github/pull_request_template.md
adminの追加をできたと思うのですがどうでしょうか。

2023-03-26 08:44 UTC, ryo-thel commented on .github/pull_request_template.md
大丈夫ですありがとうございます！

2023-03-26 09:47 UTC, ryo-thel commented on accounts/views.py
> +        return context
model=FriendShipへ変更しても，get_context_dataで新しく作成したfollower_listというコンテキストを渡しているため，object_listのクエリセットを利用していません。
今回のリストではFriendShipモデルのみ利用しているので，get_context_dataを用いるならばモデルの情報はとりあえずなしでいいと思います。

2023-03-26 09:51 UTC, ryo-thel commented on accounts/views.py
> +        return context
簡単にまとめると単一のモデルからデータを取得し、メインのクエリセットをカスタマイズする場合にはget_querysetを使用し，複数のモデルからデータを取得したい場合や、追加のデータをテンプレートに渡す必要がある場合にはget_context_dataを使用してコンテキストデータをカスタマイズするのがいいと思います！
今回はこのままでいいので参考にしてください！

2023-03-26 09:51 UTC, ryo-thel commented on accounts/views.py
> +        return super().post(request, *args, **kwargs)
ありがとうございます！

2023-03-27 09:16 UTC, yuki00900 commented on accounts/views.py
> +        return context
統一するつもりがない場合は現状のままでよいという認識で大丈夫でしょうか。

2023-03-27 09:23 UTC, yuki00900 commented on accounts/views.py
> +        return context
分かりました。
ありがとうございます。

2023-03-27 09:23 UTC, ryo-thel commented
LGTMです！

2023-03-27 18:48 UTC, masaya09 requested changes
CIに引っかかりすぎなようなので注意してください。pushしてから毎回直すのではなく、自身の環境でエラー出てないか確かめましょう。

フォーマットエラーはターミナルで、black . と打てば直せます。
構文系のエラーはターミナルで、flake8 .  と打てばどこでエラー出てるか教えてくれます。
import順の場合はターミナルで、isort . と打てば直せます。

次回からpushする前にこれらのコマンドを打って確かめてください。


画面表示に関して気になる点があったので伝えときます。ログアウトした後、ログインボタンだけでなく、サインアップボタンもあるといいですね。また、welcome/index.htmlはwelcomeアプリのtemplatesのところでなく、プロジェクトディレクトリ直下のtemplatesの方に移動させといてください。index.htmlにもサインアップボタンやログインボタンあるといいですね。どの画面からも打てるように、base.htmlにログイン、サインアップ、ログイン中はログアウトボタンを表示しておくようにするといいでしょう。

各画面に飛んだ時に、Home画面に飛べるボタンも作っとくと画面確認時に便利ですのでそこもつけてみてください。

2023-03-27 18:48 UTC, masaya09 commented on accounts/views.py
> +        )
ここの記述はget_querysetメソッドに書きましょう。follower_listという名前を使いたい場合は、context_object_name変数に代入すればいいです。詳しくは、ListViewのattributesとメソッドを[こちら](https://ccbv.co.uk/projects/Django/4.1/django.views.generic.list/ListView/)から確認してください。

2023-03-27 18:48 UTC, masaya09 commented on accounts/views.py
> +            return HttpResponseBadRequest("自分をフォローすることはできません。")
```suggestion
        if self.kwargs["username"] == request.user.username:
            return HttpResponseBadRequest("自分をフォローすることはできません。")
        following = get_object_or_404(User, username=self.kwargs["username"])
```
UnFollowViewに合わせた方がここでは良さそうですね。理由は、request.user.usernameが一致した段階でreturnされるので、無駄にクエリが走らないようになりそうだからです。

とはいえどちらが先でもそこまで大差ないので、どちらもでもいいです。ただ、FollowView, UnFollowVIewどちらかに書き方は統一してください

2023-03-27 18:48 UTC, masaya09 commented on accounts/views.py
> +        )
ここも同様

2023-03-27 18:48 UTC, masaya09 commented on templates/accounts/profile.html
> +  {% endif %}
message表示させてないので削除

2023-03-27 18:48 UTC, masaya09 commented on templates/accounts/profile.html
> +  <form action="{%  url 'accounts:follow' user.username %}" method="POST">{% csrf_token %}
８行目ではobject.usernameとしてるのに、こちらではuser.usernameとしてるのはよくないので、どちらかに統一してください

2023-03-28 06:32 UTC, yuki00900 commented on accounts/views.py
> +        )
やってみたのですが理解することができず、userとcontextがダメになってしまったので
どのように直せばよいのか教えてほしいです。

また、他に指摘されたことは直せたと思うのですがどうでしょうか。

2023-03-28 07:04 UTC, masaya09 requested changes

2023-03-28 07:04 UTC, masaya09 commented on templates/index.html
> +</body>
bodyタグ2つ使ってしまってる。ここに関しては、base.htmlをextendsして用いましょう。base.htmlの方に、サインアップ、ログイン、ログアウトボタンを記述してるので、base.htmlをextendsすればここの、サインアップやログインボタンは不要です。

2023-03-28 07:04 UTC, masaya09 commented on templates/base.html
>    <a href={% url "accounts:logout" %}>ログアウト</a>
is_authenticatedがtrueの時にホームボタン、ログアウトボタンを表示するようにし、falseの時にサインアップ、ログインボタンを表示した方が良いです

2023-03-28 07:10 UTC, masaya09 commented on accounts/views.py
> +        )
下記のような形になります
```
class FollowingListView(LoginRequiredMixin, generic.ListView):
    ...
    context_object_name = "~"

    def get_queryset(self):
        get_context_dataで取得しようとしていたFriendShipデータのクエリをここに記述する
```

2023-03-28 07:59 UTC, masaya09 requested changes

2023-03-28 09:01 UTC, masaya09 requested changes

2023-03-28 09:01 UTC, masaya09 commented on templates/index.html
> +{% endblock %}
block contentの中にbodyタグ入れてしまうと、bodyタグがbase.htmlのと合わせて2つになってしまいます

2023-03-28 14:13 UTC, masaya09 approved these changes
LGTM

2023-03-28 14:13 UTC, merged