Likes
shinonome-inc/backend-final-assignment-yuki-Yuki-Takami pull request #6
Opened 2023-04-22 11:42 UTC by yuki00900

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-04-23 02:32 UTC, HasegawaKota commented on templates/base.html
> +  <script src="{% static 'like.js' %}"></script>
base.htmlは全画面に共通することだけを記載するのでjsファイルなどは書かなくて良いと思います

2023-04-23 02:32 UTC, HasegawaKota commented on templates/base.html
> +{% load static %}
ここも

2023-04-23 02:32 UTC, HasegawaKota commented on templates/tweets/detail.html
>  <a href="{% url 'tweets:delete' tweet.pk %}"><button type="button">削除</button></a>
ここに追加してjsファイルもincludeしてあげてください

2023-04-23 02:32 UTC, HasegawaKota commented on templates/tweets/home.html
>  {% endfor %}
ここに追加してjsファイルもincludeしてあげてください

2023-04-23 03:02 UTC, HasegawaKota commented on templates/tweets/like.html
> +{% if tweet.id in liked_list %}
今の状態だと、「いいね」押した、「いいね解除」押したに関わらず、ページ遷移したら必ず「いいね」ボタンが出てきてしまいます。ここを直してもらいたいです。ぱっと見た感じliked_listは定義されていないのでいつも「いいね」しかページ遷移した時に出てこないのかと。確認してみてください

2023-04-23 13:42 UTC, h-iwasaki083 commented
先にBootCamp中にちょっとだけ言ったフォロワー一覧についてだけ

accounts/views.pyの91行目で、
filter(follower=user)
となっていて、混乱するところなのですがこれではslugにユーザーネームが入っているユーザー(＝フォロワーを一覧で表示したい対象のユーザー)がフォローされているユーザーでフィルターをかけていることになっています。
（followerではなく、followeeとかで置き換えてみると分かり易いかも…！）

それなのにselect_relatedではfollowerでINNER JOINしてしまっているため、うまくデータが取って来られていない、というような状況です。うまく説明できないのがもどかしいですが、、もし説明が分かりにくかったら教えてください泣

長々と書きましたが解決法はとても単純で、91行目でフィルター掛けているところを
filter(following=user)
と修正すれば解決💯
ひとつ前で記述しているFollowingListViewと following / follower を対照的にすればいいという風に考えても間違えに気づきやすいかもしれないです◎

2023-04-23 13:42 UTC, h-iwasaki083 reviewed
先にBootCamp中にちょっとだけ言ったフォロワー一覧についてだけ

accounts/views.pyの91行目で、
filter(follower=user)
となっていて、混乱するところなのですがこれではslugにユーザーネームが入っているユーザー(＝フォロワーを一覧で表示したい対象のユーザー)がフォローされているユーザーでフィルターをかけていることになっています。
（followerではなく、followeeとかで置き換えてみると分かり易いかも…！）

それなのにselect_relatedではfollowerでINNER JOINしてしまっているため、うまくデータが取って来られていない、というような状況です。うまく説明できないのがもどかしいですが、、もし説明が分かりにくかったら教えてください泣

長々と書きましたが解決法はとても単純で、91行目でフィルター掛けているところを
filter(following=user)
と修正すれば解決💯
ひとつ前で記述しているFollowingListViewと following / follower を対照的にすればいいという風に考えても間違えに気づきやすいかもしれないです◎

2023-04-25 06:56 UTC, h-iwasaki083 reviewed
遅くなってごめんなさい！コメントのご確認お願いします。
いいねの数がリロードすると消えてしまう問題に関してはちょっともう少し考えさせて下さい…！🙇‍♀️

また、今回の範囲と直接は関係ないのですが、クラスベース汎用ビューを継承するときに、accountsアプリではgenericをインポートしたあとにviews.pyの中でgeneric.~~Viewというような表記になっている反面、tweetsアプリでは最初にdjango.views.genericからそれぞれのviewをインポートしているのが気になります。機能上問題はないですが、統一した方が見やすいかなと思うので余力があれば修正してみて下さい！

2023-04-25 06:56 UTC, h-iwasaki083 commented on templates/tweets/like.html
> +{% if tweet.id in liked_list %}
ここに補足です
ここは、対象のツイートがliked_listというコンテキストに入っているときにこのif文の中に書かれた処理が走ることを示しています。（具体的にはいいね解除という表示が反映され、likeという関数が実行されます。）
そのため、このif文を機能させるためには、like.htmlと紐づいているViewにliked_listというコンテキストがあることが前提条件になります。

今回の場合はlike.htmlと紐づいているView、すなわち{% include "tweets/like.html" %}を書いたテンプレートに紐づいているVIewはHomeView、UserProfileView、TweetDetailViewの3つです。このそれぞれにliked_listというコンテキストが創られているか確認し、なければ追加してみてください👀

2023-04-26 10:34 UTC, h-iwasaki083 reviewed
修正内容OKです！
リロードするといいね数が消えてしまう問題についてご確認お願いします。
あと[こっち](https://github.com/shinonome-inc/backend-final-assignment-yuki-Yuki-Takami/pull/6#pullrequestreview-1399211852)のViewの継承に関しても良ければ…！

2023-04-26 10:34 UTC, h-iwasaki083 commented on templates/tweets/like.html
> +<div id="count_{{tweet.id}}">{{tweet.liked_count}}</div>
ここでは該当ツイートのいいね数を表示させる処理を書きます。

最終課題の中で{{ }}の中にはコンテキストの名前を入れることが多かったですが、ドットを利用することでオブジェクトとその属性にアクセスすることが出来ます。今回の場合は、表示したいlikeオブジェクトのtweet属性をTweetオブジェクトにINNER JOINします。それを、viewで書いてきたのと同じように
`[オブジェクト名].[inner joinしたい属性のrelated_name]`
というように書けば取得することができます。

また、オブジェクトにあるメソッドはテンプレート上でも同様に呼び出すことができます。フォロー機能を作成する際にUserProfileViewでフォロー数・フォロワー数を表示するためのコンテキストを作ったときと同様に、countメソッドを適用してみてください！

[参考1 テンプレートタグ](https://docs.djangoproject.com/ja/4.1/ref/templates/language/#variables)
[参考2 メソッドへのアクセス](https://docs.djangoproject.com/ja/4.1/ref/templates/language/#accessing-method-calls)

私もこのあたり感覚でなんとなく掴んでいるだけで細かい部分の説明まで正確に分かりやすくできている自信がないので、もしよく分からなかったら教えてください🙏

2023-04-27 17:34 UTC, h-iwasaki083 reviewed
リロードしなくてもいいね数が消えずに更新されるようになりました✨Viewの継承元の統一もありがとうございます。

毎度長文すみません、あと2点だけご確認よろしくお願いします！

2023-04-27 17:34 UTC, h-iwasaki083 commented on static/like.js
> +    count.innerHTML = tweet_data.liked_count;
これを書いていることによって、画面遷移することなくいいねの数を更新することが出来ています！！
ただ、countという定数は30行目で
`const count = document.querySelector(`#count_${tweet_data.tweet_id}`)`
つまり、like.htmlの `<div id="count_{{tweet.id}}">`と`</div>` タグで囲まれた全体を指しています。
ここにhtmlファイルでは"いいね数"という文字列と、いいねの数値データが入っています。

一方、like_countには数値データのみが格納されており、"いいね数"という文字列が非同期処理の後に消えてしまっています（＝リロードしないと復活しない）。これを防ぐためには、JavaScriptファイルのinnerHTMLメソッドに"いいね数"という文字列を追加してあげる必要があります。全体を ` ` で囲って、変数の部分のみ ${ 変数 } のような形にしてみてあげてください👀

2023-04-27 17:34 UTC, h-iwasaki083 commented on static/like.js
> +    count.innerHTML = tweet_data.liked_count;
ここも同様です◎

2023-04-27 17:34 UTC, h-iwasaki083 commented on tweets/tests.py
> +        self.assertEqual(Tweet.objects.count(), 1)
ここは元々書いていた方がテスト項目要件に合っていたので、戻しておいて下さい！
TweetDeleteViewの引数をgeneric.DeleteViewに合わせた時に同時にUserPassesTestMixinを消してしまったため、ツイートを投稿したユーザー以外がツイートを削除しようとしてもそれが禁止されない（＝403Forbiddenにならない）ためだと思われます。ツイート数が減ってしまうのも正しくないです。

UserPassesTestMixinについて、
参考1：[公式ドキュメント](https://docs.djangoproject.com/ja/4.2/topics/auth/default/#django.contrib.auth.mixins.UserPassesTestMixin)
参考2：[もう少し分かり易そうなサイト](https://qiita.com/chanyou0311/items/31a4380d11c904563c86)

※ 今回はUserPassesTestMixinをオーバーライドする必要はないです。

2023-04-28 02:47 UTC, h-iwasaki083 approved these changes
1次レビューOKです！
JavaScriptファイルの変数を含む文字列の扱いに関してだけ修正しておいてください！

2023-04-28 02:47 UTC, h-iwasaki083 commented on static/like.js
> +    count.innerHTML = "いいね数 ${tweet_data.liked_count}";
ややこしいんですがダブルクオーテーションではなくて、「`」←これで囲まないと変数の部分が認識されないみたいです...！
シングルクオーテーションでもなくて、キーボードにもよりますが恐らくshift+@で出てくると思います！！🙇‍♀️

2023-04-28 02:47 UTC, h-iwasaki083 commented on static/like.js
> +    count.innerHTML = "いいね数 ${tweet_data.liked_count}";
こっちも！

2023-04-28 03:12 UTC, Akinori13 requested changes
とても良い感じです！ちょこっとだけコメントしました！

2023-04-28 03:12 UTC, Akinori13 commented on static/like.js
> +  console.log(tweet)
これは削除しましょう

2023-04-28 03:12 UTC, Akinori13 commented on static/like.js
> +  console.log(count)
これも削除しましょう

2023-04-28 03:12 UTC, Akinori13 commented on templates/tweets/detail.html
> +{% if request.user.is_authenticated and tweet.user == request.user %}
`request.user.is_authenticated`は必要ですか？

2023-04-28 03:18 UTC, Akinori13 commented
LGTM！

2023-04-28 03:18 UTC, Akinori13 approved these changes

2023-04-28 03:18 UTC, merged